<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
        
    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    const Countries = [
        'AFG' => ["id" => 1, "name" => 'AFGHANISTAN', "code" => 'AFG'],
        'ALB' => ["id" => 2, "name" => 'ALBANIA', "code" => 'ALB'],
        'DZA' => ["id" => 3, "name" => 'ALGERIA', "code" => 'DZA'],
        'ASM' => ["id" => 4, "name" => 'AMERICAN SAMOA', "code" => 'ASM'],
        'AND' => ["id" => 5, "name" => 'ANDORRA', "code" => 'AND'],
        'AGO' => ["id" => 6, "name" => 'ANGOLA', "code" => 'AGO'],
        'AIA' => ["id" => 7, "name" => 'ANGUILLA', "code" => 'AIA'],
        'ATA' => ["id" => 8, "name" => 'ANTARCTICA', "code" => 'ATA'],
        'ATG' => ["id" => 9, "name" => 'ANTIGUA AND BARBUDA', "code" => 'ATG'],
        'ARG' => ["id" => 10, "name" => 'ARGENTINA', "code" => 'ARG'],
        'ARM' => ["id" => 11, "name" => 'ARMENIA', "code" => 'ARM'],
        'ABW' => ["id" => 12, "name" => 'ARUBA', "code" => 'ABW'],
        'AUS' => ["id" => 13, "name" => 'AUSTRALIA', "code" => 'AUS'],
        'AUT' => ["id" => 14, "name" => 'AUSTRIA', "code" => 'AUT'],
        'AZE' => ["id" => 15, "name" => 'AZERBAIJAN', "code" => 'AZE'],
        'BHS' => ["id" => 16, "name" => 'BAHAMAS', "code" => 'BHS'],
        'BHR' => ["id" => 17, "name" => 'BAHRAIN', "code" => 'BHR'],
        'BGD' => ["id" => 18, "name" => 'BANGLADESH', "code" => 'BGD'],
        'BRB' => ["id" => 19, "name" => 'BARBADOS', "code" => 'BRB'],
        'BLR' => ["id" => 20, "name" => 'BELARUS', "code" => 'BLR'],
        'BEL' => ["id" => 21, "name" => 'BELGIUM', "code" => 'BEL'],
        'BLZ' => ["id" => 22, "name" => 'BELIZE', "code" => 'BLZ'],
        'BEN' => ["id" => 23, "name" => 'BENIN', "code" => 'BEN'],
        'BMU' => ["id" => 24, "name" => 'BERMUDA', "code" => 'BMU'],
        'BTN' => ["id" => 25, "name" => 'BHUTAN', "code" => 'BTN'],
        'BOL' => ["id" => 26, "name" => 'BOLIVIA', "code" => 'BOL'],
        'BIH' => ["id" => 27, "name" => 'BOSNIA AND HERZEGOVINA', "code" => 'BIH'],
        'BWA' => ["id" => 28, "name" => 'BOTSWANA', "code" => 'BWA'],
        'BVT' => ["id" => 29, "name" => 'BOUVET ISLAND', "code" => 'BVT'],
        'BRA' => ["id" => 30, "name" => 'BRAZIL', "code" => 'BRA'],
        'IOT' => ["id" => 31, "name" => 'BRITISH INDIAN OCEAN TERRITORY', "code" => 'IOT'],
        'BRN' => ["id" => 32, "name" => 'BRUNEI DARUSSALAM', "code" => 'BRN'],
        'BGR' => ["id" => 33, "name" => 'BULGARIA', "code" => 'BGR'],
        'BFA' => ["id" => 34, "name" => 'BURKINA FASO', "code" => 'BFA'],
        'BDI' => ["id" => 35, "name" => 'BURUNDI', "code" => 'BDI'],
        'KHM' => ["id" => 36, "name" => 'CAMBODIA', "code" => 'KHM'],
        'CMR' => ["id" => 37, "name" => 'CAMEROON', "code" => 'CMR'],
        'CAN' => ["id" => 38, "name" => 'CANADA', "code" => 'CAN'],
        'CPV' => ["id" => 39, "name" => 'CAPE VERDE', "code" => 'CPV'],
        'CYM' => ["id" => 40, "name" => 'CAYMAN ISLANDS', "code" => 'CYM'],
        'CAF' => ["id" => 41, "name" => 'CENTRAL AFRICAN REPUBLIC', "code" => 'CAF'],
        'TCD' => ["id" => 42, "name" => 'CHAD', "code" => 'TCD'],
        'CHL' => ["id" => 43, "name" => 'CHILE', "code" => 'CHL'],
        'CHN' => ["id" => 44, "name" => 'CHINA', "code" => 'CHN'],
        'CXR' => ["id" => 45, "name" => 'CHRISTMAS ISLAND', "code" => 'CXR'],
        'CCK' => ["id" => 46, "name" => 'COCOS (KEELING) ISLANDS', "code" => 'CCK'],
        'COL' => ["id" => 47, "name" => 'COLOMBIA', "code" => 'COL'],
        'COM' => ["id" => 48, "name" => 'COMOROS', "code" => 'COM'],
        'COG' => ["id" => 49, "name" => 'CONGO', "code" => 'COG'],
        'COD' => ["id" => 50, "name" => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', "code" => 'COD'],
        'COK' => ["id" => 51, "name" => 'COOK ISLANDS', "code" => 'COK'],
        'CRI' => ["id" => 52, "name" => 'COSTA RICA', "code" => 'CRI'],
        'CIV' => ["id" => 53, "name" => 'COTE D\'IVOIRE', "code" => 'CIV'],
        'HRV' => ["id" => 54, "name" => 'CROATIA', "code" => 'HRV'],
        'CUB' => ["id" => 55, "name" => 'CUBA', "code" => 'CUB'],
        'CYP' => ["id" => 56, "name" => 'CYPRUS', "code" => 'CYP'],
        'CZE' => ["id" => 57, "name" => 'CZECH REPUBLIC', "code" => 'CZE'],
        'DNK' => ["id" => 58, "name" => 'DENMARK', "code" => 'DNK'],
        'DJI' => ["id" => 59, "name" => 'DJIBOUTI', "code" => 'DJI'],
        'DMA' => ["id" => 60, "name" => 'DOMINICA', "code" => 'DMA'],
        'DOM' => ["id" => 61, "name" => 'DOMINICAN REPUBLIC', "code" => 'DOM'],
        'ECU' => ["id" => 62, "name" => 'ECUADOR', "code" => 'ECU'],
        'EGY' => ["id" => 63, "name" => 'EGYPT', "code" => 'EGY'],
        'SLV' => ["id" => 64, "name" => 'EL SALVADOR', "code" => 'SLV'],
        'GNQ' => ["id" => 65, "name" => 'EQUATORIAL GUINEA', "code" => 'GNQ'],
        'ERI' => ["id" => 66, "name" => 'ERITREA', "code" => 'ERI'],
        'EST' => ["id" => 67, "name" => 'ESTONIA', "code" => 'EST'],
        'ETH' => ["id" => 68, "name" => 'ETHIOPIA', "code" => 'ETH'],
        'FLK' => ["id" => 69, "name" => 'FALKLAND ISLANDS (MALVINAS)', "code" => 'FLK'],
        'FRO' => ["id" => 70, "name" => 'FAROE ISLANDS', "code" => 'FRO'],
        'FJI' => ["id" => 71, "name" => 'FIJI', "code" => 'FJI'],
        'FIN' => ["id" => 72, "name" => 'FINLAND', "code" => 'FIN'],
        'FRA' => ["id" => 73, "name" => 'FRANCE', "code" => 'FRA'],
        'GUF' => ["id" => 74, "name" => 'FRENCH GUIANA', "code" => 'GUF'],
        'PYF' => ["id" => 75, "name" => 'FRENCH POLYNESIA', "code" => 'PYF'],
        'ATF' => ["id" => 76, "name" => 'FRENCH SOUTHERN TERRITORIES', "code" => 'ATF'],
        'GAB' => ["id" => 77, "name" => 'GABON', "code" => 'GAB'],
        'GMB' => ["id" => 78, "name" => 'GAMBIA', "code" => 'GMB'],
        'GEO' => ["id" => 79, "name" => 'GEORGIA', "code" => 'GEO'],
        'DEU' => ["id" => 80, "name" => 'GERMANY', "code" => 'DEU'],
        'GHA' => ["id" => 81, "name" => 'GHANA', "code" => 'GHA'],
        'GIB' => ["id" => 82, "name" => 'GIBRALTAR', "code" => 'GIB'],
        'GRC' => ["id" => 83, "name" => 'GREECE', "code" => 'GRC'],
        'GRL' => ["id" => 84, "name" => 'GREENLAND', "code" => 'GRL'],
        'GRD' => ["id" => 85, "name" => 'GRENADA', "code" => 'GRD'],
        'GLP' => ["id" => 86, "name" => 'GUADELOUPE', "code" => 'GLP'],
        'GUM' => ["id" => 87, "name" => 'GUAM', "code" => 'GUM'],
        'GTM' => ["id" => 88, "name" => 'GUATEMALA', "code" => 'GTM'],
        'GIN' => ["id" => 89, "name" => 'GUINEA', "code" => 'GIN'],
        'GNB' => ["id" => 90, "name" => 'GUINEA-BISSAU', "code" => 'GNB'],
        'GUY' => ["id" => 91, "name" => 'GUYANA', "code" => 'GUY'],
        'HTI' => ["id" => 92, "name" => 'HAITI', "code" => 'HTI'],
        'HMD' => ["id" => 93, "name" => 'HEARD ISLAND AND MCDONALD ISLANDS', "code" => 'HMD'],
        'VAT' => ["id" => 94, "name" => 'HOLY SEE (VATICAN CITY STATE)', "code" => 'VAT'],
        'HND' => ["id" => 95, "name" => 'HONDURAS', "code" => 'HND'],
        'HKG' => ["id" => 96, "name" => 'HONG KONG', "code" => 'HKG'],
        'HUN' => ["id" => 97, "name" => 'HUNGARY', "code" => 'HUN'],
        'ISL' => ["id" => 98, "name" => 'ICELAND', "code" => 'ISL'],
        'IND' => ["id" => 99, "name" => 'INDIA', "code" => 'IND'],
        'IDN' => ["id" => 100, "name" => 'INDONESIA', "code" => 'IDN'],
        'IRN' => ["id" => 101, "name" => 'IRAN, ISLAMIC REPUBLIC OF', "code" => 'IRN'],
        'IRQ' => ["id" => 102, "name" => 'IRAQ', "code" => 'IRQ'],
        'IRL' => ["id" => 103, "name" => 'IRELAND', "code" => 'IRL'],
        'ISR' => ["id" => 104, "name" => 'ISRAEL', "code" => 'ISR'],
        'ITA' => ["id" => 105, "name" => 'ITALY', "code" => 'ITA'],
        'JAM' => ["id" => 106, "name" => 'JAMAICA', "code" => 'JAM'],
        'JPN' => ["id" => 107, "name" => 'JAPAN', "code" => 'JPN'],
        'JOR' => ["id" => 108, "name" => 'JORDAN', "code" => 'JOR'],
        'KAZ' => ["id" => 109, "name" => 'KAZAKHSTAN', "code" => 'KAZ'],
        'KEN' => ["id" => 110, "name" => 'KENYA', "code" => 'KEN'],
        'KIR' => ["id" => 111, "name" => 'KIRIBATI', "code" => 'KIR'],
        'PRK' => ["id" => 112, "name" => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', "code" => 'PRK'],
        'KOR' => ["id" => 113, "name" => 'KOREA, REPUBLIC OF', "code" => 'KOR'],
        'KWT' => ["id" => 114, "name" => 'KUWAIT', "code" => 'KWT'],
        'KGZ' => ["id" => 115, "name" => 'KYRGYZSTAN', "code" => 'KGZ'],
        'LAO' => ["id" => 116, "name" => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', "code" => 'LAO'],
        'LVA' => ["id" => 117, "name" => 'LATVIA', "code" => 'LVA'],
        'LBN' => ["id" => 118, "name" => 'LEBANON', "code" => 'LBN'],
        'LSO' => ["id" => 119, "name" => 'LESOTHO', "code" => 'LSO'],
        'LBR' => ["id" => 120, "name" => 'LIBERIA', "code" => 'LBR'],
        'LBY' => ["id" => 121, "name" => 'LIBYAN ARAB JAMAHIRIYA', "code" => 'LBY'],
        'LIE' => ["id" => 122, "name" => 'LIECHTENSTEIN', "code" => 'LIE'],
        'LTU' => ["id" => 123, "name" => 'LITHUANIA', "code" => 'LTU'],
        'LUX' => ["id" => 124, "name" => 'LUXEMBOURG', "code" => 'LUX'],
        'MAC' => ["id" => 125, "name" => 'MACAO', "code" => 'MAC'],
        'MKD' => ["id" => 126, "name" => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', "code" => 'MKD'],
        'MDG' => ["id" => 127, "name" => 'MADAGASCAR', "code" => 'MDG'],
        'MWI' => ["id" => 128, "name" => 'MALAWI', "code" => 'MWI'],
        'MYS' => ["id" => 129, "name" => 'MALAYSIA', "code" => 'MYS'],
        'MDV' => ["id" => 130, "name" => 'MALDIVES', "code" => 'MDV'],
        'MLI' => ["id" => 131, "name" => 'MALI', "code" => 'MLI'],
        'MLT' => ["id" => 132, "name" => 'MALTA', "code" => 'MLT'],
        'MHL' => ["id" => 133, "name" => 'MARSHALL ISLANDS', "code" => 'MHL'],
        'MTQ' => ["id" => 134, "name" => 'MARTINIQUE', "code" => 'MTQ'],
        'MRT' => ["id" => 135, "name" => 'MAURITANIA', "code" => 'MRT'],
        'MUS' => ["id" => 136, "name" => 'MAURITIUS', "code" => 'MUS'],
        'MYT' => ["id" => 137, "name" => 'MAYOTTE', "code" => 'MYT'],
        'MEX' => ["id" => 138, "name" => 'MEXICO', "code" => 'MEX'],
        'FSM' => ["id" => 139, "name" => 'MICRONESIA, FEDERATED STATES OF', "code" => 'FSM'],
        'MDA' => ["id" => 140, "name" => 'MOLDOVA, REPUBLIC OF', "code" => 'MDA'],
        'MCO' => ["id" => 141, "name" => 'MONACO', "code" => 'MCO'],
        'MNG' => ["id" => 142, "name" => 'MONGOLIA', "code" => 'MNG'],
        'MSR' => ["id" => 143, "name" => 'MONTSERRAT', "code" => 'MSR'],
        'MAR' => ["id" => 144, "name" => 'MOROCCO', "code" => 'MAR'],
        'MOZ' => ["id" => 145, "name" => 'MOZAMBIQUE', "code" => 'MOZ'],
        'MMR' => ["id" => 146, "name" => 'MYANMAR', "code" => 'MMR'],
        'NAM' => ["id" => 147, "name" => 'NAMIBIA', "code" => 'NAM'],
        'NRU' => ["id" => 148, "name" => 'NAURU', "code" => 'NRU'],
        'NPL' => ["id" => 149, "name" => 'NEPAL', "code" => 'NPL'],
        'NLD' => ["id" => 150, "name" => 'NETHERLANDS', "code" => 'NLD'],
        'ANT' => ["id" => 151, "name" => 'NETHERLANDS ANTILLES', "code" => 'ANT'],
        'NCL' => ["id" => 152, "name" => 'NEW CALEDONIA', "code" => 'NCL'],
        'NZL' => ["id" => 153, "name" => 'NEW ZEALAND', "code" => 'NZL'],
        'NIC' => ["id" => 154, "name" => 'NICARAGUA', "code" => 'NIC'],
        'NER' => ["id" => 155, "name" => 'NIGER', "code" => 'NER'],
        'NGA' => ["id" => 156, "name" => 'NIGERIA', "code" => 'NGA'],
        'NIU' => ["id" => 157, "name" => 'NIUE', "code" => 'NIU'],
        'NFK' => ["id" => 158, "name" => 'NORFOLK ISLAND', "code" => 'NFK'],
        'MNP' => ["id" => 159, "name" => 'NORTHERN MARIANA ISLANDS', "code" => 'MNP'],
        'NOR' => ["id" => 160, "name" => 'NORWAY', "code" => 'NOR'],
        'OMN' => ["id" => 161, "name" => 'OMAN', "code" => 'OMN'],
        'PAK' => ["id" => 162, "name" => 'PAKISTAN', "code" => 'PAK'],
        'PLW' => ["id" => 163, "name" => 'PALAU', "code" => 'PLW'],
        'PAN' => ["id" => 164, "name" => 'PANAMA', "code" => 'PAN'],
        'PNG' => ["id" => 165, "name" => 'PAPUA NEW GUINEA', "code" => 'PNG'],
        'PRY' => ["id" => 166, "name" => 'PARAGUAY', "code" => 'PRY'],
        'PER' => ["id" => 167, "name" => 'PERU', "code" => 'PER'],
        'PHL' => ["id" => 168, "name" => 'PHILIPPINES', "code" => 'PHL'],
        'PCN' => ["id" => 169, "name" => 'PITCAIRN', "code" => 'PCN'],
        'POL' => ["id" => 170, "name" => 'POLAND', "code" => 'POL'],
        'PRT' => ["id" => 171, "name" => 'PORTUGAL', "code" => 'PRT'],
        'PRI' => ["id" => 172, "name" => 'PUERTO RICO', "code" => 'PRI'],
        'QAT' => ["id" => 173, "name" => 'QATAR', "code" => 'QAT'],
        'REU' => ["id" => 174, "name" => 'REUNION', "code" => 'REU'],
        'ROU' => ["id" => 175, "name" => 'ROMANIA', "code" => 'ROU'],
        'RUS' => ["id" => 176, "name" => 'RUSSIAN FEDERATION', "code" => 'RUS'],
        'RWA' => ["id" => 177, "name" => 'RWANDA', "code" => 'RWA'],
        'SHN' => ["id" => 178, "name" => 'SAINT HELENA', "code" => 'SHN'],
        'KNA' => ["id" => 179, "name" => 'SAINT KITTS AND NEVIS', "code" => 'KNA'],
        'LCA' => ["id" => 180, "name" => 'SAINT LUCIA', "code" => 'LCA'],
        'SPM' => ["id" => 181, "name" => 'SAINT PIERRE AND MIQUELON', "code" => 'SPM'],
        'VCT' => ["id" => 182, "name" => 'SAINT VINCENT AND THE GRENADINES', "code" => 'VCT'],
        'WSM' => ["id" => 183, "name" => 'SAMOA', "code" => 'WSM'],
        'SMR' => ["id" => 184, "name" => 'SAN MARINO', "code" => 'SMR'],
        'STP' => ["id" => 185, "name" => 'SAO TOME AND PRINCIPE', "code" => 'STP'],
        'SAU' => ["id" => 186, "name" => 'SAUDI ARABIA', "code" => 'SAU'],
        'SEN' => ["id" => 187, "name" => 'SENEGAL', "code" => 'SEN'],
        'SYC' => ["id" => 188, "name" => 'SEYCHELLES', "code" => 'SYC'],
        'SLE' => ["id" => 189, "name" => 'SIERRA LEONE', "code" => 'SLE'],
        'SGP' => ["id" => 190, "name" => 'SINGAPORE', "code" => 'SGP'],
        'SVK' => ["id" => 191, "name" => 'SLOVAKIA', "code" => 'SVK'],
        'SVN' => ["id" => 192, "name" => 'SLOVENIA', "code" => 'SVN'],
        'SLB' => ["id" => 193, "name" => 'SOLOMON ISLANDS', "code" => 'SLB'],
        'SOM' => ["id" => 194, "name" => 'SOMALIA', "code" => 'SOM'],
        'ZAF' => ["id" => 195, "name" => 'SOUTH AFRICA', "code" => 'ZAF'],
        'SGS' => ["id" => 196, "name" => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', "code" => 'SGS'],
        'ESP' => ["id" => 197, "name" => 'SPAIN', "code" => 'ESP'],
        'LKA' => ["id" => 198, "name" => 'SRI LANKA', "code" => 'LKA'],
        'SDN' => ["id" => 199, "name" => 'SUDAN', "code" => 'SDN'],
        'SUR' => ["id" => 200, "name" => 'SURINAME', "code" => 'SUR'],
        'SJM' => ["id" => 201, "name" => 'SVALBARD AND JAN MAYEN', "code" => 'SJM'],
        'SWZ' => ["id" => 202, "name" => 'SWAZILAND', "code" => 'SWZ'],
        'SWE' => ["id" => 203, "name" => 'SWEDEN', "code" => 'SWE'],
        'CHE' => ["id" => 204, "name" => 'SWITZERLAND', "code" => 'CHE'],
        'SYR' => ["id" => 205, "name" => 'SYRIAN ARAB REPUBLIC', "code" => 'SYR'],
        'TWN' => ["id" => 206, "name" => 'TAIWAN, PROVINCE OF CHINA', "code" => 'TWN'],
        'TJK' => ["id" => 207, "name" => 'TAJIKISTAN', "code" => 'TJK'],
        'TZA' => ["id" => 208, "name" => 'TANZANIA, UNITED REPUBLIC OF', "code" => 'TZA'],
        'THA' => ["id" => 209, "name" => 'THAILAND', "code" => 'THA'],
        'TLS' => ["id" => 210, "name" => 'TIMOR-LESTE', "code" => 'TLS'],
        'TGO' => ["id" => 211, "name" => 'TOGO', "code" => 'TGO'],
        'TKL' => ["id" => 212, "name" => 'TOKELAU', "code" => 'TKL'],
        'TON' => ["id" => 213, "name" => 'TONGA', "code" => 'TON'],
        'TTO' => ["id" => 214, "name" => 'TRINIDAD AND TOBAGO', "code" => 'TTO'],
        'TUN' => ["id" => 215, "name" => 'TUNISIA', "code" => 'TUN'],
        'TUR' => ["id" => 216, "name" => 'TURKEY', "code" => 'TUR'],
        'TKM' => ["id" => 217, "name" => 'TURKMENISTAN', "code" => 'TKM'],
        'TCA' => ["id" => 218, "name" => 'TURKS AND CAICOS ISLANDS', "code" => 'TCA'],
        'TUV' => ["id" => 219, "name" => 'TUVALU', "code" => 'TUV'],
        'UGA' => ["id" => 220, "name" => 'UGANDA', "code" => 'UGA'],
        'UKR' => ["id" => 221, "name" => 'UKRAINE', "code" => 'UKR'],
        'ARE' => ["id" => 222, "name" => 'UNITED ARAB EMIRATES', "code" => 'ARE'],
        'GBR' => ["id" => 223, "name" => 'UNITED KINGDOM', "code" => 'GBR'],
        'USA' => ["id" => 224, "name" => 'UNITED STATES', "code" => 'USA'],
        'URY' => ["id" => 225, "name" => 'URUGUAY', "code" => 'URY'],
        'UZB' => ["id" => 226, "name" => 'UZBEKISTAN', "code" => 'UZB'],
        'VUT' => ["id" => 227, "name" => 'VANUATU', "code" => 'VUT'],
        'VEN' => ["id" => 228, "name" => 'VENEZUELA', "code" => 'VEN'],
        'VNM' => ["id" => 229, "name" => 'VIET NAM', "code" => 'VNM'],
        'VGB' => ["id" => 230, "name" => 'VIRGIN ISLANDS, BRITISH', "code" => 'VGB'],
        'VIR' => ["id" => 231, "name" => 'VIRGIN ISLANDS, U.S.', "code" => 'VIR'],
        'WLF' => ["id" => 232, "name" => 'WALLIS AND FUTUNA', "code" => 'WLF'],
        'ESH' => ["id" => 233, "name" => 'WESTERN SAHARA', "code" => 'ESH'],
        'YEM' => ["id" => 234, "name" => 'YEMEN', "code" => 'YEM'],
        'ZMB' => ["id" => 235, "name" => 'ZAMBIA', "code" => 'ZMB'],
        'ZWE' => ["id" => 236, "name" => 'ZIMBABWE', "code" => 'ZWE'],
        'JEY' => ["id" => 237, "name" => 'JERSEY', "code" => 'JEY'],
        'GGY' => ["id" => 238, "name" => 'GUERNSEY', "code" => 'GGY'],
        'UNK' => ["id" => 239, "name" => 'UNKNOWN', "code" => 'UNK'],
        'IMN' => ["id" => 240, "name" => 'ISLE OF MAN', "code" => 'IMN'],
    ];
}
